### ISSUE TITLE
Home - Hero section

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#1]
![Screen Shot 2022-10-07 at 1 27 37 PM](https://user-images.githubusercontent.com/62365335/194615603-7cfb1f12-7750-4228-8295-2c64755696be.png)

First section on home page. Background image is in public/images. Full Figma is here: https://www.figma.com/file/I03uCw196ZjlzxHQelByBU/Landing-Page

**Comment by flubbypuppy** [comment]
Please assign this to me!

**Comment by aryamankha** [comment]
Assigned this to you!
