### ISSUE TITLE
Profile - Fan page

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#11]
<img width="412" alt="Screen Shot 2022-10-08 at 2 06 47 PM" src="https://user-images.githubusercontent.com/62365335/194721447-dffbe5c1-04e5-4bfe-b9dc-32b7ed76a91f.png">

Profile page for fans. Full Figma design: https://www.figma.com/file/aTnodnfVNVkOus9dLZ5U96/Profile-Page

**Comment by Omkar0803** [comment]
Hey @aryamankha can you assign this to me

**Comment by Omkar0803** [comment]
hey @aryamankha Do we have to integrate wallet interaction?

**Comment by aryamankha** [comment]
No wallet integration needed for now (unless you want to take that on) - will assign this task to you

**Comment by aryamankha** [comment]
I'll create a separate issue for the wallet integration after the database has been set up
