### ISSUE TITLE
Home - What's it all about section

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#2]
![Screen Shot 2022-10-07 at 1 23 21 PM](https://user-images.githubusercontent.com/62365335/194614887-2ee90b7c-24c2-492d-a52e-edd3e40e797a.png)

What's it all about section. Second section on home page. Full Figma - https://www.figma.com/file/I03uCw196ZjlzxHQelByBU/Landing-Page

**Comment by IsabellaSoares** [comment]
Hi @aryamankha! Please assign this to me!

**Comment by aryamankha** [comment]
Assigning it to you!

**Comment by Omkar0803** [comment]
I would like to contribute, can assign me issues?

**Comment by Omkar0803** [comment]
Hey @aryamankha, if it is taking too much time, can I give it a shot, please assign me.
