### ISSUE TITLE
Browse page

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#21]
<img width="713" alt="Screen Shot 2022-10-10 at 11 31 27 AM" src="https://user-images.githubusercontent.com/62365335/194902694-8593dad8-fa44-45c6-9233-e85d2b189cbf.png">

Create browse page without search functionality. Will add new issue for search functionality once DB is set up. Full Figma here: https://www.figma.com/file/8RpbZL9OlzJIYUR4k0rTlb/Browse-Page

**Comment by Omkar0803** [comment]
Please assignthis issue too, I can complete it within 2days

**Comment by Omkar0803** [comment]
Will definitely try Vivid!
