### ISSUE TITLE
Consolidate nav bars

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#22]
We currently have two different nav bars, one on the main page, and a separate one on the /profile page. Consolidate those two nav bars into one, make it a separate component, and have it display on both pages.

**Comment by Omkar0803** [comment]
Hey @aryamankha please , assign me this issue

**Comment by aryamankha** [comment]
Assigned to you!

**Comment by Omkar0803** [comment]
Yeah!, but I have one doubt, the navbar at the hero section contains a sign-up button and on the profile page it is MetaMask.

**Comment by Omkar0803** [comment]
Currently I have kept metamask button

**Comment by aryamankha** [comment]
That should be fine for now
