### ISSUE TITLE
Edit "What's it all about section" with new images and copy

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#26]
![Screen Shot 2022-10-10 at 2 35 50 PM](https://user-images.githubusercontent.com/62365335/194931724-a1920a15-4adc-4b48-b588-9a5d80e8a9fa.png)

Images are located in public/images

**Comment by redxzeta** [comment]
can i work on this

**Comment by aryamankha** [comment]
Assigning it to you!

**Comment by aryamankha** [comment]
@redxzeta The PR you submitted doesn't implement the design in the issue. Please resubmit if you're still interested, or I can reassign it to someone else

**Comment by redxzeta** [comment]
> @redxzeta The PR you submitted doesn't implement the design in the issue. Please resubmit if you're still interested, or I can reassign it to someone else

So include the text ?

**Comment by aryamankha** [comment]
Yes - include the text and no borders around the images.

**Comment by aryamankha** [comment]
Making those edits should be super easy with Vivid! Just Option-click on anything you see on the screen to modify its code.

**Comment by redxzeta** [comment]
Okay will do
