### ISSUE TITLE
Home - Latest Drops Section

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#3]
![Screen Shot 2022-10-07 at 1 24 32 PM](https://user-images.githubusercontent.com/62365335/194615098-2f20eb56-bd26-40bc-bfd8-f401f7085d4e.png)

Latest Drops section. Third section on home page. Full Figma - https://www.figma.com/file/I03uCw196ZjlzxHQelByBU/Landing-Page

**Comment by umeshchavda05** [comment]
hey @aryamankha can i work on this?

**Comment by aryamankha** [comment]
Yes! Assigning to you

**Comment by Omkar0803** [comment]
I  would also like to contribute

**Comment by Omkar0803** [comment]
Hey @aryamankha, might the issue is taking much time, I can solve this issue and having some ideas related to it.
