### ISSUE TITLE
Home - FAQs section 

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#4]
![Screen Shot 2022-10-07 at 1 25 26 PM](https://user-images.githubusercontent.com/62365335/194615320-a6818827-1945-4d10-8275-76312c74bfce.png)

FAQs section. Last section on home page. Full Figma - https://www.figma.com/file/I03uCw196ZjlzxHQelByBU/Landing-Page

**Comment by IsabellaSoares** [comment]
Hi @aryamankha! Please assign this to me!

**Comment by aryamankha** [comment]
Sounds great! Assigning it to you

**Comment by Omkar0803** [comment]
I would like to contribute, can assign me issues?
