### ISSUE TITLE
Make "What's it all about" section responsive

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#42]

**Comment by UditNS** [comment]
Hi @aryamankha, I want to work on this issue.

**Comment by aryamankha** [comment]
Great! Assigning you to it

**Comment by UditNS** [comment]
Working on it.

**Comment by UditNS** [comment]
Hi, I have completed the task. Do you want any changes to do ?

<img width="328" alt="Screenshot 2022-10-13 at 6 19 57 AM" src="https://user-images.githubusercontent.com/102902271/195474525-6f5de77b-c513-4b45-b19e-70c95e41196e.png">

<img width="335" alt="Screenshot 2022-10-13 at 6 21 42 AM" src="https://user-images.githubusercontent.com/102902271/195474545-80a53982-7b2f-489d-9d8a-8b59b1376600.png">

**Comment by aryamankha** [comment]
That's great! If you could just
