### ISSUE TITLE
Change profile picture to reflect sign in from Auth0

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#44]
Currently, profile picture in top right of nav bar is static regardless of sign in. Change nav bar so that if user is not signed in, only "sign up" button shows up in top right. If user is signed in, add their profile picture in the nav bar and include the "Metamask" button.

**Comment by jsvigneshkanna** [comment]
Please assign this feature to my name, will build it soon

**Comment by jsvigneshkanna** [comment]
Will add auth0 to sign in

**Comment by aryamankha** [comment]
Auth0 has already been added, just needs to be reflected in the rest of the site's functionality
