### ISSUE TITLE
Add SignIn and Signout button

### ISSUE THREAD

**Issue by jsvigneshkanna** [aryamankha/backstage-hacktoberfest#48]
@aryamankha 

Description:

Currently there is only signup button.
It would be user-friendly to show signin button in navbar in logout session and signout button in loggedin session

Please assign this issue to my name, will implement this feature

**Comment by jsvigneshkanna** [comment]
Hi @aryamankha ,
Can you check this new feature

**Comment by aryamankha** [comment]
Great idea - adding you to it.
