### ISSUE TITLE
Header/Nav Bar

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#5]
![Screen Shot 2022-10-07 at 1 26 28 PM](https://user-images.githubusercontent.com/62365335/194615478-ab8b9766-9d54-4569-82ed-c6b6e47eb34f.png)

Sticky Nav Bar. Full Figma - https://www.figma.com/file/I03uCw196ZjlzxHQelByBU/Landing-Page

**Comment by hrsh22** [comment]
I would like to contribute. Can you assign it to me?

**Comment by aryamankha** [comment]
Yes! Go for it

**Comment by Omkar0803** [comment]
I also like to contribute, can you assign me too?

**Comment by hrsh22** [comment]
![Screenshot ](https://user-images.githubusercontent.com/90423812/194753744-299cd55c-3ccf-4057-b8e9-284234a2a7e7.png)
I have completed the Navbar. Should I send the pull request?

**Comment by aryamankha** [comment]
Yes! Submit a PR

**Comment by aryamankha** [comment]
@Omkar0803 We’ll find some more issues for you to contribute on!
