### ISSUE TITLE
Profile - star page

### ISSUE THREAD

**Issue by aryamankha** [aryamankha/backstage-hacktoberfest#8]
![Screen Shot 2022-10-07 at 5 26 49 PM](https://user-images.githubusercontent.com/62365335/194657546-a1b76cbe-cb9b-4716-ae13-df706210c516.png)

Frontend for profile page for musicians dropping NFTs. Full Figma - https://www.figma.com/file/aTnodnfVNVkOus9dLZ5U96/Profile-Page?node-id=0%3A1

**Comment by vazqueztomas** [comment]
I would like to contribute on this!

**Comment by aryamankha** [comment]
Great! Assigning to you

**Comment by Omkar0803** [comment]
I would like to contribute, can assign me issues?

**Comment by mhetreayush** [comment]
I am experienced in making screes, please assign it to me

**Comment by aryamankha** [comment]
@Omkar0803 @mhetreayush We have some other issues open if you want to choose one of them!

**Comment by aryamankha** [comment]
Hey @vazqueztomas - what is the progress looking like on this?

**Comment by vazqueztomas** [comment]
Hey @aryamankha ! You can see it, i've already opened a PR.
